### ISSUE TITLE
Add admaven

### ISSUE THREAD

**Issue by llacb47** [ameshkov/circumvention-monitor#4]
Example sites:
```
https://www.downloadpirate.com/adobe-premiere-pro-cc-2019-13-1-3-44-full-version-cracked-pre-activated/
https://www.watchtvseries.video/the-real-housewives-of-beverly-hills-10x04-episode-4/
https://moviegaga.to/movie/prodigal-son-season-1-7y1ne4m2/watch#2vgzemyzp42l4xjq
```

**Comment by ameshkov** [comment]
@llacb47 could you please also say what domains are random/rotating on these websites so that I knew where to look?

**Comment by ameshkov** [comment]
Is that it?
https://d3pvcolmug0tz6.cloudfront.net/?ocvpd=675718
https://ds88pc0kw6cvc.cloudfront.net/?kcpsd=849337

Do they always use cloudfront?

**Comment by ameshkov** [comment]
Build result:
https://github.com/ameshkov/circumvention-monitor/commit/f022609abdc2424e079ebdfe3be9ccb559d9edc4#diff-fab7cf1c7eaa442d18c567c7a104ed8a

Please check if all the necessary domains are added there

**Comment by llacb47** [comment]
Also they use domains with suffix `site`.
```
originedreting.site
merciselyancies.site
successarysazh.site
```

**Comment by llacb47** [comment]
@ameshkov ?

**Comment by ameshkov** [comment]
Sorry, I've been a little busy lately. I'll try checking this tomorrow

**Comment by llacb47** [comment]
Hi @ameshkov ,

this is actually admaven. Can you please move it when you get a chance? https://github.com/ameshkov/circumvention-monitor/commit/a6d65ac93953a33b98069e8dd6f081e156d8a4d9

**Comment by ameshkov** [comment]
@llacb47 done: https://github.com/ameshkov/circumvention-monitor/commit/5a19b24a63156a89dc5b5e4b433df32a1db35105

Feel free to create pull requests if you don't want to wait for me:)
